# Generated by Django 4.0.3 on 2022-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
